Repository lienflash/lienflash-fe, pull requests merged in 2020-10, with the labels that each got.

#27 Add logo and basic styling to header
  src/assets/lienflash-logo.png
  src/containers/Header/Header.js
  src/containers/Header/Header.scss
Labels: FE, Phase 2, enhancement

#30 Sn feature/job form
  package-lock.json
  package.json
  src/components/JobFormStepOne/JobFormStepOne.js
  src/components/JobFormStepOne/JobFormStepOne.test.js
  src/components/JobFormStepTwo/JobFormStepTwo.js
  src/components/JobFormStepTwo/JobFormStepTwo.test.js
  src/containers/App/App.js
  src/containers/JobForm/JobForm.js
  src/containers/JobForm/JobForm.scss
  src/containers/JobForm/JobForm.test.js
Labels: FE, Phase 2, enhancement

#32 Display Jobs View
  package-lock.json
  package.json
  src/actions/actions.js
  src/actions/actions.test.js
  src/containers/App/App.js
  src/containers/App/App.scss
  src/containers/Header/Header.js
  src/containers/Header/Header.scss
  src/containers/Header/Header.test.js
  src/containers/Homepage/Homepage.scss
  src/containers/JobCard/JobCard.js
  src/containers/JobCard/JobCard.scss
  src/containers/JobCard/JobCard.test.js
  src/containers/Jobs/Jobs.js
  src/containers/Jobs/Jobs.scss
  src/containers/Jobs/Jobs.test.js
  src/helpers/apiCalls.js
  src/index.js
  src/reducers/index.js
  src/reducers/jobsReducer.js
  src/reducers/jobsReducer.test.js
Labels: FE, Phase 2, enhancement

#33 Sn testing/app homepage
  src/components/JobFormStepOne/JobFormStepOne.js
  src/components/JobFormStepTwo/JobFormStepTwo.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/Header/Header.js
  src/containers/Homepage/Homepage.js
  src/containers/Homepage/Homepage.test.js
  src/containers/JobCard/JobCard.js
  src/containers/JobForm/JobForm.js
  src/containers/JobForm/JobForm.scss
  src/scss/_app.scss
  src/scss/_buttons.scss
  src/scss/_fonts.scss
  src/scss/_header.scss
  src/scss/_homepage.scss
  src/scss/_jobCard.scss
  src/scss/_jobForm.scss
  src/scss/_media_queries.scss
  src/scss/_variables.scss
  src/scss/styles.scss
Labels: FE, Phase 2, enhancement

#35 Sn feature/post request
  src/components/Homepage/Homepage.test.js
  src/components/JobDetails/JobDetails.js
  src/components/JobDetails/JobDetails.test.js
  src/components/JobFormStepOne/JobFormStepOne.js
  src/components/JobFormStepOne/JobFormStepOne.test.js
  src/components/JobFormStepTwo/JobFormStepTwo.js
  src/components/JobFormStepTwo/JobFormStepTwo.test.js
  src/containers/App/App.js
  src/containers/JobForm/JobForm.js
  src/helpers/apiCalls.js
Labels: Phase 2

#46 Sn/testing
  src/actions/actions.test.js
  src/components/JobFormStepOne/JobFormStepOne.test.js
  src/components/JobFormStepTwo/JobFormStepTwo.test.js
  src/containers/App/App.js
  src/containers/JobForm/JobForm.js
  src/containers/JobForm/JobForm.test.js
  src/reducers/jobInfoReducer.test.js
Labels: testing

#48 Sn feature/pwa 1
  public/images/apple-icon-120.jpg
  public/images/apple-icon-152.jpg
  public/images/apple-icon-167.jpg
  public/images/apple-icon-180.jpg
  public/images/apple-splash-1125-2436.jpg
  public/images/apple-splash-1136-640.jpg
  public/images/apple-splash-1242-2208.jpg
  public/images/apple-splash-1242-2688.jpg
  public/images/apple-splash-1334-750.jpg
  public/images/apple-splash-1536-2048.jpg
  public/images/apple-splash-1620-2160.jpg
  public/images/apple-splash-1668-2224.jpg
  public/images/apple-splash-1668-2388.jpg
  public/images/apple-splash-1792-828.jpg
  public/images/apple-splash-2048-1536.jpg
  public/images/apple-splash-2048-2732.jpg
  public/images/apple-splash-2160-1620.jpg
  public/images/apple-splash-2208-1242.jpg
  public/images/apple-splash-2224-1668.jpg
  public/images/apple-splash-2388-1668.jpg
  public/images/apple-splash-2436-1125.jpg
  public/images/apple-splash-2688-1242.jpg
  public/images/apple-splash-2732-2048.jpg
  public/images/apple-splash-640-1136.jpg
  public/images/apple-splash-750-1334.jpg
  public/images/apple-splash-828-1792.jpg
  public/images/icons-512.png
  public/images/manifest-icon-192.png
  public/images/manifest-icon-512.png
  public/index.html
  public/manifest.json
  public/worker.js
  src/index.js
Labels: FE
