Repository lienflash/lienflash-fe, pull requests merged in 2020-11, with the labels that each got.

#68 Sn/update statuses
  package-lock.json
  package.json
  src/components/JobFormStepOne/JobFormStepOne.test.js
  src/components/UserMessage/UserMessage.js
  src/components/UserMessage/UserMessage.test.js
  src/containers/App/App.js
  src/containers/JobDetails/JobDetails.js
  src/containers/JobDetails/JobDetails.test.js
  src/containers/JobForm/JobForm.test.js
  src/helpers/apiCalls.js
  src/reducers/jobInfoReducer.js
  src/reducers/jobsReducer.js
  src/scss/_buttons.scss
  src/scss/_jobDetails.scss
Labels: enhancement

#69 Tm/integration tests
  src/components/Homepage/Homepage.test.js
  src/components/JobForm/JobForm.js
  src/components/JobForm/JobForm.test.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/Header/Header.js
  src/containers/JobCard/JobCard.js
  src/containers/JobCard/JobCard.scss
  src/containers/JobCard/JobCard.test.js
  src/containers/JobDetails/JobDetails.js
  src/containers/JobDetails/JobDetails.test.js
  src/containers/Jobs/Jobs.js
Labels: FE, Phase 2, testing

#70 Tm/login feature
  src/actions/actions.js
  src/actions/actions.test.js
  src/components/Homepage/Homepage.js
  src/components/Homepage/Homepage.test.js
  src/components/JobForm/JobForm.js
  src/components/JobForm/JobForm.test.js
  src/components/LandingPage/LandingPage.js
  src/components/LandingPage/LandingPage.test.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/Header/Header.js
  src/containers/Header/Header.test.js
  src/containers/JobDetails/JobDetails.test.js
  src/containers/Jobs/Jobs.js
  src/containers/Jobs/Jobs.test.js
  src/containers/Login/Login.js
  src/containers/Login/Login.test.js
  src/helpers/apiCalls.js
  src/reducers/index.js
  src/reducers/jobInfoReducer.js
  src/reducers/jobInfoReducer.test.js
  src/reducers/jobsReducer.js
  src/reducers/jobsReducer.test.js
  src/reducers/userReducer.js
  src/reducers/userReducer.test.js
  src/scss/_buttons.scss
  src/scss/_jobForm.scss
Labels: FE, enhancement, phase 3, testing

#71 Sn feature/profile
  src/components/JobForm/JobForm.js
  src/components/JobForm/JobForm.test.js
  src/containers/App/App.js
  src/containers/App/App.test.js
  src/containers/JobDetails/JobDetails.js
  src/containers/JobDetails/JobDetails.test.js
  src/containers/Profile/Profile.js
  src/containers/Profile/Profile.test.js
  src/helpers/apiCalls.js
  src/scss/_jobDetails.scss
  src/scss/_variables.scss
Labels: FE, enhancement

#74 Sn/testingv2
  src/components/Homepage/Homepage.js
  src/components/Homepage/Homepage.test.js
  src/components/JobForm/JobForm.js
  src/components/JobForm/JobForm.test.js
  src/components/JobFormStepOne/JobFormStepOne.js
  src/components/JobFormStepTwo/JobFormStepTwo.js
  src/components/LandingPage/LandingPage.js
  src/components/LandingPage/LandingPage.test.js
  src/components/Loader/Loader.js
  src/components/Loader/Loader.test.js
  src/components/UserMessage/UserMessage.js
  src/components/UserMessage/UserMessage.test.js
  src/containers/App/App.js
  src/containers/JobCard/JobCard.test.js
  src/containers/JobDetails/JobDetails.js
  src/containers/JobDetails/JobDetails.test.js
  src/containers/Jobs/Jobs.test.js
  src/containers/Profile/Profile.js
  src/containers/Profile/Profile.test.js
  src/helpers/apiCalls.js
  src/reducers/jobsReducer.test.js
  src/reducers/userReducer.test.js
Labels: testing

#92 Tm/create user feature
  src/components/LandingPage/LandingPage.js
  src/containers/App/App.js
  src/containers/CreateUser/CreateUser.js
  src/containers/CreateUser/CreateUser.test.js
  src/containers/Header/Header.js
  src/containers/Header/Header.test.js
  src/helpers/apiCalls.js
Labels: FE, enhancement, phase 3, testing
